name: Sync File from Repo A

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B (This Repository)
        uses: actions/checkout@v3

      - name: Fetch File from Repo A
        run: |
          curl -sSf -o Whitelist.txt https://raw.githubusercontent.com/Stalker-Classic/SCWhitelist/refs/heads/main/SCWhitelist.txt

      - name: Check for Changes
        run: |
          git diff --quiet && exit 0  # Exit if no changes
          git add Whitelist.txt
          git commit -m "Auto-sync Whitelist.txt from Repo A"
          git push
