name: Sync File from Repo A

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B (This Repository)
        uses: actions/checkout@v3

      - name: Fetch File from Repo A
        run: |
          curl -sSf -o Test.txt https://raw.githubusercontent.com/Shazie-Items/Whitelist/main/Test.txt

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check for Changes and Push
        run: |
          git add Test.txt
          git diff --cached --quiet && exit 0  # Exit if no changes
          git commit -m "Auto-sync Test.txt from Repo A"
          git push
