name: Sync File from Repo A

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B (This Repository)
        uses: actions/checkout@v3

      - name: Fetch File from Repo A
        run: |
          curl -sSf -o Test.txt https://raw.githubusercontent.com/Shazie-Items/Whitelist/main/Test.txt

      - name: Replace Content of Whitelist2.txt with Test.txt
        run: |
          cp Test.txt Whitelist2.txt  # Replace Whitelist2.txt content with Test.txt

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check for Changes and Push
        run: |
          git add Whitelist2.txt  # Now we're adding Whitelist2.txt
          git diff --cached --quiet && exit 0  # Exit if no changes
          git commit -m "Auto-sync Whitelist2.txt with Test.txt from Repo A"
          git push

