name: Sync File from Repo A

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B (This Repository)
        uses: actions/checkout@v3

      - name: Print current date and time
        run: date  # Debugging step to check the run time

      - name: Fetch File from Repo A
        run: |
          curl -sSf -o SCWhitelist.txt https://raw.githubusercontent.com/Stalker-Classic/SCWhitelist/main/SCWhitelist.txt

      - name: Replace Content of Whitelist2.txt with SCWhitelist.txt
        run: |
          cp SCWhitelist.txt Whitelist2.txt  # Replace Whitelist2.txt content with SCWhitelist.txt

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Authenticate and Push Changes with PAT
        run: |
          git remote set-url origin https://github-actions:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Shazie-Items/Whitelist.git
          git add Whitelist2.txt
          git diff --cached --quiet && exit 0  # Exit if no changes
          git commit -m "Auto-sync Whitelist2.txt with SCWhitelist.txt from Repo A"
          git push
